### ISSUE TITLE
kube-nas: setup observability

### ISSUE THREAD

**Issue by jazzlyn** [tyriis/home-ops#3851]
### Todos

- [ ] setup thanos or mimir in talos-flux
- [ ] setup prometheus (3d retention) in kube-nas
- [ ] setup thanos or mimir connection in kube-nas
- [ ] setup promtail/vector (send logs to cloud or talos-flux)
- [ ] (setup alerts)

**Comment by jazzlyn** [comment]
```
Cluster 1:                    Cluster 2:
[Prometheus + Sidecar]        [Prometheus + Sidecar]
         ↓                             ↓
    [MinIO/S3]                    [MinIO/S3]
         ↓                             ↓
         └────── [Thanos Query] ──────┘
                       ↓
                   [Grafana]
```
